include:
  - project: mattermost/ci/$CI_PROJECT_NAME
    ref: setup-gitlab
    file: private.yml

stages:
  - test
  - build

test:
#   image: $CI_REGISTRY/qa/images/android-node:android-32_node-16.14.2-20220426
  image: cimg/android:2022.03-node
  stage: test
  variables:
    KUBERNETES_CPU_REQUEST: 3
    KUBERNETES_CPU_LIMIT: 5
    KUBERNETES_MEMORY_REQUEST: 5Gi
    KUBERNETES_MEMORY_LIMIT: 6Gi
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 512Mi
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 1Gi

    KUBERNETES_HELPER_CPU_REQUEST: 1
    KUBERNETES_HELPER_CPU_LIMIT: 2
    KUBERNETES_HELPER_MEMORY_REQUEST: 1Gi
    KUBERNETES_HELPER_MEMORY_LIMIT: 2Gi
    KUBERNETES_HELPER_EPHEMERAL_STORAGE_REQUEST: 256Mi
    KUBERNETES_HELPER_EPHEMERAL_STORAGE_LIMIT: 500Mi

    KUBERNETES_SERVICE_CPU_REQUEST: 0
    KUBERNETES_SERVICE_CPU_LIMIT: 0
    KUBERNETES_SERVICE_MEMORY_REQUEST: 0
    KUBERNETES_SERVICE_MEMORY_LIMIT: 0
    KUBERNETES_SERVICE_EPHEMERAL_STORAGE_REQUEST: 0
    KUBERNETES_SERVICE_EPHEMERAL_STORAGE_LIMIT: 0

    COMPASS_ICONS: "node_modules/@mattermost/compass-icons/font/compass-icons.ttf"
    NODE_OPTIONS: --max_old_space_size=12000
    NODE_ENV: production
    BABEL_ENV: production
    NODE_PARAM_VERSION: 16.14.2
    BASHRC_FILE: "$CI_BUILDS_DIR/.bashrc"
  cache:
  - key:
      files:
        - package-lock.json
    paths:
      - .npm/
  - key: assets-cache-$CI_COMMIT_REF_SLUG
    paths:
      - dist
  before_script:
    - touch $BASHRC_FILE
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    - echo 'export NVM_DIR="$HOME/.nvm"' > $BASHRC_FILE
    - echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use' >> $BASHRC_FILE
    # shellcheck source=/dev/null
    - source $BASHRC_FILE;
    - nvm install "$NODE_PARAM_VERSION"
    - nvm alias default "$NODE_PARAM_VERSION"
    - echo 'nvm use default &>/dev/null' >> $BASHRC_FILE

    - NODE_ENV=development npm ci --cache .npm --ignore-scripts
    - npx patch-package
    - node scripts/generate-assets.js
    - cp "$COMPASS_ICONS" "assets/fonts/"
    - cp "$COMPASS_ICONS" "android/app/src/main/assets/fonts"
  script:
    - npm run check
    - npm test
    - bash scripts/precommit/i18n.sh
  retry:
    max: 2
    when:
      - runner_system_failure
