include:
  - project: mattermost/ci/$CI_PROJECT_NAME
    ref: setup-gitlab
    file: private.yml

stages:
  - test
  - build

test:
#   image: $CI_REGISTRY/qa/images/android-node:android-32_node-16.14.2-20220426
  image: cimg/node:16.14.2
  stage: test
  variables:
    KUBERNETES_CPU_REQUEST: 3
    KUBERNETES_CPU_LIMIT: 5
    KUBERNETES_MEMORY_REQUEST: 5Gi
    KUBERNETES_MEMORY_LIMIT: 6Gi
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 512Mi
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 1Gi

    KUBERNETES_HELPER_CPU_REQUEST: 1
    KUBERNETES_HELPER_CPU_LIMIT: 2
    KUBERNETES_HELPER_MEMORY_REQUEST: 1Gi
    KUBERNETES_HELPER_MEMORY_LIMIT: 2Gi
    KUBERNETES_HELPER_EPHEMERAL_STORAGE_REQUEST: 256Mi
    KUBERNETES_HELPER_EPHEMERAL_STORAGE_LIMIT: 500Mi

    KUBERNETES_SERVICE_CPU_REQUEST: 0
    KUBERNETES_SERVICE_CPU_LIMIT: 0
    KUBERNETES_SERVICE_MEMORY_REQUEST: 0
    KUBERNETES_SERVICE_MEMORY_LIMIT: 0
    KUBERNETES_SERVICE_EPHEMERAL_STORAGE_REQUEST: 0
    KUBERNETES_SERVICE_EPHEMERAL_STORAGE_LIMIT: 0

    COMPASS_ICONS: "node_modules/@mattermost/compass-icons/font/compass-icons.ttf"
  cache:
  - key:
      files:
        - package-lock.json
    paths:
      - .npm/
  - key: assets-cache-$CI_COMMIT_REF_SLUG
    paths:
      - dist
  before_script:
#     - NODE_ENV=development npm update --legacy-peer-deps
    - NODE_ENV=development npm ci --cache .npm --ignore-scripts --legacy-peer-deps
    - npx patch-package
    - node scripts/generate-assets.js
    - cp "$COMPASS_ICONS" "assets/fonts/"
    - cp "$COMPASS_ICONS" "android/app/src/main/assets/fonts"
  script:
    - npm run check
    - npm test
    - bash scripts/precommit/i18n.sh
  retry:
    max: 2
    when:
      - runner_system_failure
